account/urls.py
from django.urls import include, path
from . import views

app_name = 'account'
urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('profile', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', views.home, name='home')
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jop_app.urls', namespace='jobsssss')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.ForeignKey(
        "City", on_delete=models.CASCADE, null=True, blank=True)
    phone = models.CharField(max_length=15)
    image = models.ImageField(upload_to='profile/')

    def __str__(self):
        return f'{self.user.username} Profile'


# once create new user, create new empty profile
@receiver(post_save, sender=User)  # => User model will be the sender
def create_user_profile(sender, instance, created, **kwargs):
    if created:  # => When a new instance of User created
        # => Instantiate a new Profile object and make its user field refers to that created User object.
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name} '

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class Signup_Form(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("city", "phone", "image")


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")

account/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import Signup_Form, ProfileForm, UserForm
from django.contrib.auth import authenticate, login
from .models import Profile

# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = Signup_Form(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/accounts/profile')
    else:
        form = Signup_Form()

    return render(request, 'registration/signup.html', {'form': form})


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'accounts/profile.html', {'profile': profile})


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        userform = UserForm(request.POST, instance=request.user)
        profileform = ProfileForm(
            request.POST, request.FILES, instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myProfile = profileform.save(commit=False)
            myProfile.user = request.user
            myProfile.save()
            return redirect(reverse('accounts:profile'))
        pass
    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)
    return render(request, 'accounts/profile_edit.html', {'userform': userform, 'profileform': profileform})

account/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>Profile Details</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Name: <span>{{profile.user.username}}</span></li>
                            <li>Email: <span>{{profile.user.email}}</span></li>
                            <li>City: <span>{{profile.city}}</span></li>
                            <li>Phone: <span>{{profile.phone}}</span></li>
                            <!-- <li>Image: <span><img src="{{profile.image.url}}" alt="dfsdgdgs"
                                        style="max-width:100px"></span></li> -->
                        </ul>
                    </div>
                    <div class="p-5">
                        <a href="{% url 'accounts:profile_edit' %}" class="boxed-btn3 w-100">Edit profile</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

account/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Edit Profile</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <div class="apply_job_form white-bg">
                    <h4>Edit Profile</h4>
                    {% comment %} ##################### Add form for the job ######################## {% endcomment %}
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form userform %}
                        {% bootstrap_form profileform %}
                        {%buttons%}
                        <button class="boxed-btn3 w-100" type="submit">Save</button>
                        {%endbuttons%}
                    </form>
                </div>

            </div>
        </div>
    </div>

    {% endblock body %}