account/urls.py
from django.urls import include, path
from . import views

app_name = 'account'
urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('profile', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

jop_app/urls.py
from django.urls import include, path
from . import views
from . import api

app_name = 'jop_appppppppppp'
urlpatterns = [
    # VIEWs
    path('', views.jop_list, name='jobs'),
    path('add', views.add_job, name='add_job'),
    path('<str:slug>', views.jop_detail, name='job_detailsssssss'),

    # APIs :
    # Function based
    path('api/jobs', api.job_list_api, name='job_list_api'),
    path('api/jobs/<int:id>', api.job_detail_api, name='job_detail_api'),

    # class based
    path('api/v2/jobs', api.JopListApi.as_view(), name='job_list_api'),
    path('api/v2/jobs/<int:id>', api.JobDetail.as_view(), name='job_detail_api'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', views.home, name='home')
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jop_app.urls', namespace='jobsssss')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jop_app/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User


def image_upload(instance, filename):
    name, extention = filename.split(".")
    return f"jobs\{instance.pk}.{extention}"

# Create your models here.


class Jop(models.Model):
    # The first element in each tuple is the actual value to be set on the model,
    # and the second element is the human-readable name.
    # Make a select box with these choices instead of the standard text field.
    owner = models.ForeignKey(
        User, related_name='job_owner', on_delete=models.CASCADE)
    JOP_TYPE = [
        ("Full Time", "Full Time"),
        ("Part Time", "Part Time"),
    ]

    title = models.CharField(max_length=100)
    jop_type = models.CharField(
        max_length=15, choices=JOP_TYPE, default="Full Time")
    # location
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    Vacancy = models.IntegerField(default=1)
    Salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload)

    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Jop, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Category(models.Model):
    Name = models.CharField(max_length=25)

    def __str__(self):
        return self.Name


class Jop_Applier(models.Model):
    jop = models.ForeignKey(
        "Jop", related_name="Apply_Jop", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    website = models.URLField(max_length=200)
    cv = models.FileField(upload_to='apply/')
    cover_letter = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

jop_app/forms.py
from django import forms
from .models import Jop_Applier, Jop


class Jop_ApplierForm(forms.ModelForm):

    class Meta:
        model = Jop_Applier
        fields = ("name", "email", "website", "cv", "cover_letter")


class AddJopForm(forms.ModelForm):

    class Meta:
        model = Jop
        fields = '__all__'
        # becuase this field will be assigned when save()
        exclude = ('slug', 'owner')

jop_app/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import Jop
from .forms import Jop_ApplierForm, AddJopForm
from django.contrib.auth.decorators import login_required
from .filters import JopFilter

# Create your views here.


def jop_list(request):
    jobs_list = Jop.objects.all()

    # filter
    job_filter = JopFilter(request.GET, queryset=jobs_list)
    jobs_list = job_filter.qs

    paginator = Paginator(jobs_list, 3)  # Show 3 jops per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'jobs': page_obj, 'job_filter': job_filter}
    return render(request, 'jop_app/job_list.html', context)


def jop_detail(request, slug):
    job = Jop.objects.get(slug=slug)

    if request.method == "POST":
        # Create a form instance from POST data.
        form = Jop_ApplierForm(request.POST, request.FILES)
        if form.is_valid():
            # form.save()=> Creat and Save a new database object from the form's data.
            # form.save(commit=False)=> Creat but not Save a new database object from the form's data.
            myForm = form.save(commit=False)
            myForm.jop = job
            myForm.save()

    else:
        form = Jop_ApplierForm()

    context = {'job': job, 'form': form}
    return render(request, 'jop_app/job_detail.html', context)


@login_required
def add_job(request):
    if request.method == "POST":
        form = AddJopForm(request.POST, request.FILES)
        if form.is_valid():
            myForm = form.save(commit=False)
            myForm.owner = request.user
            myForm.save()
            return redirect(reverse('jobsssss:jobs'))
    else:
        form = AddJopForm()

    context = {'form': form}
    return render(request, 'jop_app/add_job.html', context)

jop_app/templates/jop_app/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add Jop</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">   
                    <div class="apply_job_form white-bg">
                        <h4>Add Job</h4>
                        {% comment %} ##################### Add form for the job ######################## {% endcomment %}
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %} 
                            {%buttons%}
                                <button class="boxed-btn3 w-100" type="submit">Add Now</button>
                            {%endbuttons%}
                            {% comment %} <div class="submit_btn">
                                <button class="boxed-btn3 w-100" type="submit">Add Now</button>
                            </div>  {% endcomment %}
                            {% comment %} {% csrf_token %} {% endcomment %}
                            {% comment %} <div class="row">
                                <div class="col-md-6">
                                    <div class="input_field">
                                        <input type="text" name="name" maxlength="50" required="" id="id_name" placeholder="Your name">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input_field">
                                        <input type="email" name="email" maxlength="254" required="" id="id_email" placeholder="Email">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <input type="url" name="website" maxlength="200" required="" id="id_website" placeholder="Website/Portfolio link">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button type="button" id="inputGroupFileAddon03"><i
                                                    class="fa fa-cloud-upload" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                        <div class="custom-file">
                                            <input type="file" name="cv" class="custom-file-input" required="" id="id_cv" aria-describedby="inputGroupFileAddon03">    
                                            <label class="custom-file-label" for="id_cv">Upload CV</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <textarea name="cover_letter" cols="30" rows="10" maxlength="500" required="" id="id_cover_letter" placeholder="Coverletter"></textarea>    
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </div>  {% endcomment %}
                        </form>
                    </div>
            
            </div>
        </div>
    </div>

 {% endblock body %}

jop_app/templates/jop_app/job_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#">
                                        <h4>{{job}}</h4>
                                    </a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{job.jop_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                        </div>                 
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        {% comment %} ##################### Apply for the job ######################## {% endcomment %}
                        <form method="POST" enctype="multipart/form-data">
                            {% comment %} {% csrf_token %}
                            {% bootstrap_form form %} 
                            <div class="submit_btn">
                                <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                            </div> {% endcomment %}
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input_field">
                                        <input type="text" name="name" maxlength="50" required="" id="id_name" placeholder="Your name">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input_field">
                                        <input type="email" name="email" maxlength="254" required="" id="id_email" placeholder="Email">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <input type="url" name="website" maxlength="200" required="" id="id_website" placeholder="Website/Portfolio link">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button type="button" id="inputGroupFileAddon03"><i
                                                    class="fa fa-cloud-upload" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                        <div class="custom-file">
                                            <input type="file" name="cv" class="custom-file-input" required="" id="id_cv" aria-describedby="inputGroupFileAddon03">    
                                            <label class="custom-file-label" for="id_cv">Upload CV</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <textarea name="cover_letter" cols="30" rows="10" maxlength="500" required="" id="id_cover_letter" placeholder="Coverletter"></textarea>    
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </div> 
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.published_at|date:"d M, Y"}}</span></li>
                                <li>Vacancy: <span>{{job.Vacancy}} Position</span></li>
                                <li>Salary: <span>{{job.Salary}}k/y</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span> {{job.jop_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                                function initMap() {
                                    var uluru = { lat: -25.363, lng: 131.044 };
                                    var grayStyles = [
                                        {
                                            featureType: "all",
                                            stylers: [
                                                { saturation: -90 },
                                                { lightness: 50 }
                                            ]
                                        },
                                        { elementType: 'labels.text.fill', stylers: [{ color: '#ccdee9' }] }
                                    ];
                                    var map = new google.maps.Map(document.getElementById('map'), {
                                        center: { lat: -31.197, lng: 150.744 },
                                        zoom: 9,
                                        styles: grayStyles,
                                        scrollwheel: false
                                    });
                                }

                            </script>
                            <script
                                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

 {% endblock body %}

jop_app/templates/jop_app/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs.count}}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form job_filter.form %}
                                    <input type='submit' class="boxed-btn3 w-100 mt-2" value='Search'>
                            </form>
                        </div>
                        {% comment %} <div class="range_wrap">
                            <label for="amount">Price range:</label>
                            <div id="slider-range"></div>
                            <p>
                                <input type="text" id="amount" readonly
                                    style="border:0; color:#7A838B; font-size: 14px; font-weight:400;">
                            </p>
                        </div> {% endcomment %}
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                        {% comment %} ##################### START Jop List ##################### {% endcomment %}
                        {% for job in jobs %}
                         <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            {% comment %} ========== link to job_details =========== {% endcomment %}
                                            <a href="{% url 'jobsssss:job_detailsssssss' job.slug %}">
                                                <h4>{{job}}</h4>
                                            </a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.jop_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            {% comment %} ========== link to job_details =========== {% endcomment %}
                                            <a href="{% url 'jobsssss:job_detailsssssss' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{job.published_at|date:"d M Y"}}</p>
                                            {% comment %} {{ value|date:"D d M Y" }} {% endcomment %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {% comment %} ##################### END Jop List ##################### {% endcomment %}
                        {% comment %} ##################### START Pagination ##################### {% endcomment %}
                        </div>
                        {% if jobs.has_other_pages  %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if jobs.has_previous %}
                                        <li><a href="?page={{ jobs.previous_page_number }}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in jobs.paginator.page_range %}
                                        <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if jobs.has_next %}
                                        <li><a href="?page={{ jobs.next_page_number }}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}

                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% comment %} ##################### END Pagination ##################### {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

{% endblock body %}

  